In [1]:
import chardet
import pandas as pd
import numpy as np
from scipy.spatial import distance

In [2]:
def open_with_auto_sensing_encoding_types(file_path):
    with open(file_path, 'rb') as f:
        rawdata = f.read()
        result = chardet.detect(rawdata)
        encoding_type = result['encoding']

    print(f"파일의 인코딩: {encoding_type}")
    # 감지된 인코딩으로 파일 읽기
    df = pd.read_csv(file_path, encoding=encoding_type)
    print(len(df))
    return df

In [3]:
df_path = "/Users/yujin/Desktop/파일/3-1/데이터분석 공모전/codes/키즈카페입지분석2/행정동단위통합파일_윤재.csv"
df_total = open_with_auto_sensing_encoding_types(df_path)
df_total

파일의 인코딩: utf-8
15

,Unnamed: 0,행정동명,총인구수,0~4세,5~9세,0~9세,세대당인구,실내놀이터,소득분위_1,가구수_1,소득분위_2,가구수_2,소득분위_3,가구수_3
0,0,중곡1동,15239,264,256,520,1.76,3,6분위,8508.0,6분위,8644.0,6분위,8644.0
1,1,중곡2동,20521,302,489,791,1.94,3,6분위,10545.0,6분위,10569.0,6분위,10569.0
2,2,중곡3동,15727,272,288,560,1.85,3,5분위,8551.0,5분위,8495.0,5분위,8495.0
3,3,중곡4동,27594,454,525,979,2.11,3,6분위,13163.0,6분위,13022.0,6분위,13022.0
4,4,능동,11097,220,229,449,1.71,1,6분위,6510.0,6분위,6456.0,6분위,6456.0
5,5,구의1동,23127,365,467,832,1.77,3,6분위,12108.0,6분위,12519.0,6분위,12519.0
6,6,구의2동,25610,528,772,1300,2.23,3,6분위,11685.0,6분위,11380.0,6분위,11380.0
7,7,구의3동,27840,640,867,1507,2.31,3,8분위,12201.0,8분위,12048.0,8분위,12048.0
8,8,광장동,33971,660,1716,2376,2.87,0,9분위,12065.0,9분위,11851.0,9분위,11851.0
9,9,자양1동,21833,293,398,691,1.82,3,6분위,11855.0,6분위,11960.0,6분위,11960.0
10,10,자양2동,23628,531,641,1172,2.17,3,7분위,11214.0,7분위,10890.0,7분위,10890.0
11,11,자양3동,27221,798,1053,1851,2.48,3,8분위,11170.0,8분위,10951.0,8분위,10951.0
12,12,자양4동,19883,370,425,795,1.81,3,6분위,9474.0,6분위,10929.0,6분위,10929.0
13,13,화양동,23193,164,162,326,1.28,0,6분위,17039.0,6분위,18696.0,6분위,18696.0
14,14,군자동,19070,318,396,714,1.69,0,6분위,11155.0,6분위,11293.0,6분위,11293.0

In [4]:
df_total.drop(columns=["소득분위_1","가구수_1","소득분위_2","가구수_2"], inplace=True)
df_total

    Unnamed: 0  행정동명   총인구수  0~4세  5~9세  0~9세  세대당인구  실내놀이터 소득분위_3    가구수_3
0            0  중곡1동  15239   264   256   520   1.76      3    6분위   8644.0
1            1  중곡2동  20521   302   489   791   1.94      3    6분위  10569.0
2            2  중곡3동  15727   272   288   560   1.85      3    5분위   8495.0
3            3  중곡4동  27594   454   525   979   2.11      3    6분위  13022.0
4            4    능동  11097   220   229   449   1.71      1    6분위   6456.0
5            5  구의1동  23127   365   467   832   1.77      3    6분위  12519.0
6            6  구의2동  25610   528   772  1300   2.23      3    6분위  11380.0
7            7  구의3동  27840   640   867  1507   2.31      3    8분위  12048.0
8            8   광장동  33971   660  1716  2376   2.87      0    9분위  11851.0
9            9  자양1동  21833   293   398   691   1.82      3    6분위  11960.0
10          10  자양2동  23628   531   641  1172   2.17      3    7분위  10890.0
11          11  자양3동  27221   798  1053  1851   2.48      3    8분위  10951.0
12          12  자양4동  19883   370   425   795   1.81      3    6분위  10929.0
13          13   화양동  23193   164   162   326   1.28      0    6분위  18696.0
14          14   군자동  19070   318   396   714   1.69      0    6분위  11293.0

In [22]:
print(df_total.head(15))

    행정동명   총인구수  0~4세  5~9세  0~9세  실내놀이터  소득분위      가구수  법정동
0   중곡1동  15239   264   256   520      0   6.0   8644.0  중곡동
1   중곡2동  20521   302   489   791      0   6.0  10569.0  중곡동
2   중곡3동  15727   272   288   560      0   5.0   8495.0  중곡동
3   중곡4동  27594   454   525   979      0   6.0  13022.0  중곡동
4     능동  11097   220   229   449      0   6.0   6456.0   능동
5   구의1동  23127   365   467   832      0   6.0  12519.0  구의동
6   구의2동  25610   528   772  1300      0   6.0  11380.0  구의동
7   구의3동  27840   640   867  1507      0   8.0  12048.0  구의동
8    광장동  33971   660  1716  2376      0   9.0  11851.0  광장동
9   자양1동  21833   293   398   691      0   6.0  11960.0  자양동
10  자양2동  23628   531   641  1172      0   7.0  10890.0  자양동
11  자양3동  27221   798  1053  1851      0   8.0  10951.0  자양동
12  자양4동  19883   370   425   795      0   6.0  10929.0  자양동
13   화양동  23193   164   162   326      0   6.0  18696.0  화양동
14   군자동  19070   318   396   714      0   6.0  11293.0  군자동

In [13]:
df_path2 = "/Users/yujin/Desktop/파일/3-1/데이터분석 공모전/codes/키즈카페입지분석2/법정동단위통합파일.csv"
df_2 = open_with_auto_sensing_encoding_types(df_path2)
df_2

파일의 인코딩: utf-8
7

,Unnamed: 0,법정동,총인구수,0~4세,5~9세,0~9세,실내놀이터,세대당인구,0~4세비율,5~9세비율,0~9세비율,실내놀이터당아동
0,0,광장동,33971,660,1716,2376,1,2.870000,0.019428,0.050514,0.069942,2376.00
1,1,구의동,76577,1533,2106,3639,4,2.103333,0.020019,0.027502,0.047521,909.75
2,2,군자동,19070,318,396,714,1,1.690000,0.016675,0.020766,0.037441,714.00
3,3,능동,11097,220,229,449,1,1.710000,0.019825,0.020636,0.040461,449.00
4,4,자양동,92565,1992,2517,4509,5,2.070000,0.021520,0.027192,0.048712,901.80
5,5,중곡동,79081,1292,1558,2850,5,1.915000,0.016338,0.019701,0.036039,570.00
6,6,화양동,23193,164,162,326,0,1.280000,0.007071,0.006985,0.014056,0.00

In [ ]:
# 1. 법정동별 실내놀이터 수에서 "첫 번째 값"만 추출 (first)
법정동_놀이터수 = df_2.set_index("법정동")["실내놀이터"]

# 2. df_total의 법정동 기준으로 매핑
df_total["법정동_실내놀이터"] = df_total["법정동"].map(법정동_놀이터수)

In [26]:
df_total.drop(columns=["실내놀이터"], inplace=True)
df_total

    행정동명   총인구수  0~4세  5~9세  0~9세  소득분위      가구수  법정동  법정동_실내놀이터
0   중곡1동  15239   264   256   520   6.0   8644.0  중곡동          5
1   중곡2동  20521   302   489   791   6.0  10569.0  중곡동          5
2   중곡3동  15727   272   288   560   5.0   8495.0  중곡동          5
3   중곡4동  27594   454   525   979   6.0  13022.0  중곡동          5
4     능동  11097   220   229   449   6.0   6456.0   능동          1
5   구의1동  23127   365   467   832   6.0  12519.0  구의동          4
6   구의2동  25610   528   772  1300   6.0  11380.0  구의동          4
7   구의3동  27840   640   867  1507   8.0  12048.0  구의동          4
8    광장동  33971   660  1716  2376   9.0  11851.0  광장동          1
9   자양1동  21833   293   398   691   6.0  11960.0  자양동          5
10  자양2동  23628   531   641  1172   7.0  10890.0  자양동          5
11  자양3동  27221   798  1053  1851   8.0  10951.0  자양동          5
12  자양4동  19883   370   425   795   6.0  10929.0  자양동          5
13   화양동  23193   164   162   326   6.0  18696.0  화양동          0
14   군자동  19070   318   396   714   6.0  11293.0  군자동          1

In [15]:
facility_counts = df_2["실내놀이터"]

In [19]:
print(df_2.head())

   Unnamed: 0  법정동   총인구수  0~4세  5~9세  0~9세  실내놀이터     세대당인구    0~4세비율  \
0           0  광장동  33971   660  1716  2376      1  2.870000  0.019428
1           1  구의동  76577  1533  2106  3639      4  2.103333  0.020019
2           2  군자동  19070   318   396   714      1  1.690000  0.016675
3           3   능동  11097   220   229   449      1  1.710000  0.019825
4           4  자양동  92565  1992  2517  4509      5  2.070000  0.021520

     5~9세비율    0~9세비율  실내놀이터당아동
0  0.050514  0.069942   2376.00
1  0.027502  0.047521    909.75
2  0.020766  0.037441    714.00
3  0.020636  0.040461    449.00
4  0.027192  0.048712    901.80

In [17]:
# 3. 법정동 → 행정동 매핑 딕셔너리
법정동_to_행정동 = {
    '중곡동': ['중곡1동', '중곡2동', '중곡3동', '중곡4동'],
    '구의동': ['구의1동', '구의2동', '구의3동'],
    '자양동': ['자양1동', '자양2동', '자양3동', '자양4동'],
    '화양동': ['화양동'],
    '군자동': ['군자동'],
    '능동': ['능동'],
    '광장동': ['광장동'],
}

# 4. summary_df에 "실내놀이터" 열 추가 (0으로 초기화)
df_total['실내놀이터'] = 0

# 5. 매핑을 통해 시설 개수를 행정동에 더함
for 법정동, 행정동_리스트 in 법정동_to_행정동.items():
    count = facility_counts.get(법정동, 0)
    for 행정동 in 행정동_리스트:
        df_total.loc[df_total["법정동"] == 행정동, '실내놀이터'] += count

# 결과 확인
print(df_total[['법정동', '실내놀이터']])

    법정동  실내놀이터
0   중곡동      0
1   중곡동      0
2   중곡동      0
3   중곡동      0
4    능동      0
5   구의동      0
6   구의동      0
7   구의동      0
8   광장동      0
9   자양동      0
10  자양동      0
11  자양동      0
12  자양동      0
13  화양동      0
14  군자동      0

In [6]:
df_total.rename(columns={"소득분위_3": "소득분위", "가구수_3": "가구수"}, inplace=True)

In [7]:
df_total.drop(columns=["Unnamed: 0"], inplace=True)
df_total

    행정동명   총인구수  0~4세  5~9세  0~9세  세대당인구  실내놀이터 소득분위      가구수
0   중곡1동  15239   264   256   520   1.76      3  6분위   8644.0
1   중곡2동  20521   302   489   791   1.94      3  6분위  10569.0
2   중곡3동  15727   272   288   560   1.85      3  5분위   8495.0
3   중곡4동  27594   454   525   979   2.11      3  6분위  13022.0
4     능동  11097   220   229   449   1.71      1  6분위   6456.0
5   구의1동  23127   365   467   832   1.77      3  6분위  12519.0
6   구의2동  25610   528   772  1300   2.23      3  6분위  11380.0
7   구의3동  27840   640   867  1507   2.31      3  8분위  12048.0
8    광장동  33971   660  1716  2376   2.87      0  9분위  11851.0
9   자양1동  21833   293   398   691   1.82      3  6분위  11960.0
10  자양2동  23628   531   641  1172   2.17      3  7분위  10890.0
11  자양3동  27221   798  1053  1851   2.48      3  8분위  10951.0
12  자양4동  19883   370   425   795   1.81      3  6분위  10929.0
13   화양동  23193   164   162   326   1.28      0  6분위  18696.0
14   군자동  19070   318   396   714   1.69      0  6분위  11293.0

In [27]:
df_total.to_csv("행동동단위통합파일_v2.csv")

In [20]:
df_total.columns

Index(['행정동명', '총인구수', '0~4세', '5~9세', '0~9세', '실내놀이터', '소득분위', '가구수', '법정동'], dtype='object')

In [9]:
print(df_total.head(15))

    행정동명   총인구수  0~4세  5~9세  0~9세  세대당인구  실내놀이터 소득분위      가구수
0   중곡1동  15239   264   256   520   1.76      3  6분위   8644.0
1   중곡2동  20521   302   489   791   1.94      3  6분위  10569.0
2   중곡3동  15727   272   288   560   1.85      3  5분위   8495.0
3   중곡4동  27594   454   525   979   2.11      3  6분위  13022.0
4     능동  11097   220   229   449   1.71      1  6분위   6456.0
5   구의1동  23127   365   467   832   1.77      3  6분위  12519.0
6   구의2동  25610   528   772  1300   2.23      3  6분위  11380.0
7   구의3동  27840   640   867  1507   2.31      3  8분위  12048.0
8    광장동  33971   660  1716  2376   2.87      0  9분위  11851.0
9   자양1동  21833   293   398   691   1.82      3  6분위  11960.0
10  자양2동  23628   531   641  1172   2.17      3  7분위  10890.0
11  자양3동  27221   798  1053  1851   2.48      3  8분위  10951.0
12  자양4동  19883   370   425   795   1.81      3  6분위  10929.0
13   화양동  23193   164   162   326   1.28      0  6분위  18696.0
14   군자동  19070   318   396   714   1.69      0  6분위  11293.0